# pipeline-dashboard.service
[Unit]
Description=Pipeline GUI Dashboard
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 /mnt/20TB/homelab/media/Pipeline/scripts/dashboard.py
User=topaz
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target

# pipeline-day.service
[Unit]
Description=Pipeline HARD mode - daytime

[Service]
Type=oneshot
User=topaz
ExecStart=/usr/local/bin/pipeline med

# pipeline-gc.service
[Unit]
Description=Pipeline garbage collection
After=network.target

[Service]
Type=oneshot
ExecStart=/mnt/20TB/homelab/media/Pipeline/scripts/pipeline-gc.sh
User=topaz

# pipeline-max.service
[Unit]
Description=Pipeline MAX mode - full speed

[Service]
Type=oneshot
User=topaz
ExecStart=/usr/local/bin/pipeline max

# pipeline-day.timer
[Unit]
Description=Switch pipeline to HARD mode at 12pm

[Timer]
OnCalendar=*-*-* 12:00:00
Persistent=true

[Install]
WantedBy=timers.target

# pipeline-gc.timer
[Unit]
Description=Pipeline garbage collection daily at 4 AM

[Timer]
OnCalendar=daily
OnCalendar=04:00
Persistent=true

[Install]
WantedBy=timers.target

# pipeline-max.timer
[Unit]
Description=Switch pipeline to MAX mode at 4am

[Timer]
OnCalendar=*-*-* 04:00:00
Persistent=true

[Install]
WantedBy=timers.target

